services:
    _defaults:
        autowire: true
        autoconfigure: true

    BabelForge\BabelChrome\LocalViewer\:
        resource: '../src/'
        exclude:
            - '../src/DocumentSource.php'
            - '../src/Kernel.php'
